get http://localhost:4000/products

###
get http://localhost:4000/products/1
###
post http://localhost:4000/products
Content-Type: application/json

{
    "id": 3,
    "name": "oneplus 12R"
}
###
put http://localhost:4000/products
Content-Type: application/json

{
    "id": 1,
    "name": "iphone 15plus"
}
###
delete http://localhost:4000/products/1